spring.application.name=springboot-jpa
spring.datasource.url=jdbc:postgresql://localhost:5432/db_springboot
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database.platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#Esta opcion no es para produccion, esto borra las tablas si existen y luego las vuelve a crear borrando toda la informacion.
# con true borra la base de datos y la vuelve a crear, borra todos los datos
# con update solo se sincroniza, no borra la base de datos.
spring.jpa.hibernate.ddl-auto=update