#Configuraciones, evitar caracteres especiales o configurar el archivo a UTF-8 para incluir caracteres, tildes y с.
#Para Maps recordar siempre usar comillas simples ''.
#Al usar Maps podemos anidar JSON en otros JSON haciendo un arbol.

config.code=304030
config.userName=Alex
config.message=Este es un mensaje
config.listOfValues=hola,hola2,hola3
config.internal=Este dato es un Value interno con UTF-8 бйссс
config.list=soy una list, soy una list 2, soy una list 3, soy una list n+1
config.valuesMap={product: 'Cpu Intel core i7', description: 'Alder, 12 core, 5GHz', price: 1500}